### ISSUE TITLE
7.3.1236 以降、test87 が失敗する

### ISSUE THREAD

**Issue by eagletmt** [vim-jp/issues#424]
``` diff
--- test87.ok   2013-06-27 04:56:36.000000000 +0900
+++ test87.failed   2013-06-27 12:12:35.891591990 +0900
@@ -480,12 +480,12 @@
 <<< Finished
 > VimForeachRTP
 vim.foreach_rtp(None):(<class 'TypeError'>, TypeError("'NoneType' object is not callable",))
-vim.foreach_rtp(NoArgsCall()):(<class 'TypeError'>, TypeError('__call__() takes exactly 1 positional argument (2 given)',))
+vim.foreach_rtp(NoArgsCall()):(<class 'TypeError'>, TypeError('__call__() takes 1 positional argument but 2 were given',))
 vim.foreach_rtp(FailingCall()):(<class 'NotImplementedError'>, NotImplementedError('call',))
 vim.foreach_rtp(int, 2):(<class 'TypeError'>, TypeError('foreach_rtp() takes exactly one argument (2 given)',))
 > import
-import xxx_no_such_module_xxx:(<class 'ImportError'>, ImportError('No module named xxx_no_such_module_xxx',))
-import failing_import:(<class 'ImportError'>, ImportError('No module named failing_import',))
+import xxx_no_such_module_xxx:(<class 'ImportError'>, ImportError("No module named 'xxx_no_such_module_xxx'",))
+import failing_import:(<class 'ImportError'>, ImportError("No module named 'failing_import'",))
 import failing:(<class 'NotImplementedError'>, NotImplementedError())
 > Dictionary
 >> DictionaryConstructor
```

このようにほぼ期待通りのエラーメッセージは得られているのですが、微妙に違うという状況です。
上は 7.3.1251 での結果ですが、7.3.1236 が最初に失敗するバージョンです。

使用している Python のバージョンは 3.3.2 です。
Python3 のバージョンの差によるものなんでしょうか?

**Comment by Shougo** [comment]
それはありそうですね。もしPython3.2の環境があるなら、比較してみるのはどうでしょうか。

**Comment by eagletmt** [comment]
pyenv で Python 3.2.5 を入れて同じようにビルドしてみたら全部のテストが通りました。
うーん、こういうのってどうするのがいいんですかね…

**Comment by eagletmt** [comment]
3.2.5

```
>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=2, micro=5, releaselevel='final', serial=0)
>>> import foobar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named foobar
>>> def foo(x): x
... 
>>> foo(1, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: foo() takes exactly 1 positional argument (2 given)
```

3.3.2

```
>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=3, micro=2, releaselevel='final', serial=0)
>>> import foobar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'foobar'
>>> def foo(x): x
... 
>>> foo(1, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: foo() takes 1 positional argument but 2 were given
```

**Comment by Shougo** [comment]
エラーメッセージが変更になったんですね。チェックスクリプト側で両方のエラーメッセージに対応させるか、エラーメッセージの検出条件を緩めるしかなさそうです。

**Comment by koron** [comment]
一応vim_devには報告済みです。
認識されているかは微妙なので、
援護射撃してもらえると助かります。

**Comment by k-takata** [comment]
これですね。
https://groups.google.com/d/msg/vim_dev/ceK7gHmPW0E/77VbTy7vf_IJ

**Comment by koron** [comment]
[こんなパッチ](https://bitbucket.org/koron/vim-kaoriya-patches/src/7e5076069ce9443e20d1b637e669734f14802dfc/test87_python33_workaround.diff?at=default) で対応してみました。
**3.3 の時に Exception を3.2方式へ整形するコード** が既にあったのでそれを追加する形です。

**Comment by koron** [comment]
[Posted](https://groups.google.com/d/msg/vim_dev/thdK_BeuYmY/OQxgOoGPsoAJ)

**Comment by k-takata** [comment]
7.3.1314 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/8dpjxnS-fYU/discussion
